version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysqldb

  kaddemNewv0.1:
    depends_on:
      - mysqldb
    image: jobjob1/kaddem:1.0.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/kaddem?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db:

